title: "Analyses Tactiques - Foot"
url: "https://sargejoseph.github.io/LLMshare/"
encoding: UTF-8  # Force l'encodage

remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "neon" # ou "air", "aqua", etc.
plugins:
   - jekyll-remote-theme
   - jekyll-include-cache

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules