title: "Analyses Tactiques"
url: "https://sargejoseph.github.io/LLMshare/"
encoding: UTF-8  # Force l'encodage

remote_theme: pages-themes/architect@v0.2.0
minimal_mistakes_skin: "aqua" # ou "air", "aqua", etc.
plugins:
   - jekyll-remote-theme
   - jekyll-include-cache

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules