title: "Analyses Tactiques"
url: "https://sargejoseph.github.io/LLMshare/"
encoding: UTF-8  # Force l'encodage

remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
   - jekyll-remote-theme
   - jekyll-include-cache

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules