# _config.yml corrigé
title: "Analyses Tactiques"
url: "https://sargejoseph.github.io/LLMshare/"
encoding: UTF-8  # Force l'encodage[citation:2]

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
