title: "Mes Analyses Tactiques"
   theme: minima
   include:
    
    - "*.html"  # Inclut tous les fichiers HTMLinclude:
    - .nojekyll  # Force l'inclusion des fichiers HTML bruts
   exclude:
     - Gemfile
     - Gemfile.lock
