title: "Analyses Tactiques"
url: "https://sargejoseph.github.io/LLMshare/"
encoding: UTF-8  # Force l'encodage

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      
plugins:
  - jekyll-feed  # Plugin minimal pour les builds GitHub

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
